remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

locale: "en"
title: kartikey-chauhan
title_separator: "|"
email: kartikeychauhan27@gmail.com
description: "data science, blog, kartikey chauhan"
url: "https://kartikey-chauhan.github.io" 
search: true
repository: kartikey-chauhan/kartikey-chauhan.github.io
masthead_title: " "

author:
  name: "Kartikey Chauhan"
  avatar: "assets/images/caves.jpg"
  bio: "Aspiring Data Scientist"
  location: "India"
  linkedin: "kartikeychauhan"
  github: "kartikey-chauhan"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:kartikeychauhan27@gmail.com

# breadcrumbs: true

google_site-verification : nfOijgRb5tLaTrvVb9-m4F7H3saL6q9tz5rzrMccbDE

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/kartikey-chauhan"

atom_feed:
  hide: true

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      # related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

include: ["_pages"]

comments:
  provider: "giscus"
  giscus:
    repo_id: "MDEwOlJlcG9zaXRvcnk0MDQ0MjczNTQ="
    category_name: "Announcements"
    category_id: "DIC_kwDOGBsSWs4B_Bna"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-YEXBESHXGD"
    anonymize_ip: false 

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
