remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

locale: "en"
title: carteakey
title_separator: "|"
email: kartikeychauhan27@gmail.com
description: "data science, blog, kartikey chauhan, carteakey"
url: "https://carteakey.dev"
search: true
repository: carteakey/carteakey.github.io
masthead_title: "carteakey.dev"

author:
  name: "Kartikey Chauhan"
  avatar: "assets/images/caves.jpg"
  bio: "Engineer, Developer, Learner, Procastinator"
  location: "Toronto, Canada"
  github: "carteakey"
  email: "kartikeychauhan27@gmail.com"
  linkedin: kartikeychauhan

social:
  type: Person
  name: Kartikey Chauhan
  links:
    - "https://www.linkedin.com/in/kartikeychauhan"

google_site-verification: nfOijgRb5tLaTrvVb9-m4F7H3saL6q9tz5rzrMccbDE

atom_feed:
  hide: true

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      comments: true
      share: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

comments:
  provider: "disqus"
  disqus:
    shortname: "carteakey"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-YEXBESHXGD"
    anonymize_ip: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# fixes "No GitHub API authentication" error
github: [metadata]
# breadcrumbs: true

# comments:
#   provider: "giscus"
#   giscus:
#     repo_id: "MDEwOlJlcG9zaXRvcnk0MDQ0MjczNTQ="
#     category_name: "Announcements"
#     category_id: "DIC_kwDOGBsSWs4B_Bna"
#     discussion_term: "pathname"
#     reactions_enabled: "1"
#     theme: "light"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/kartikey-chauhan"
