
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


title: kartikey chauhan
email: kartikeychauhan27@gmail.com
description: "data science, kartikey chauhan, blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kartikey-chauhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name     : "Kartikey Chauhan"
  avatar   : "images/caves.jpg"
  bio      : "Aspiring Data Scientist"
  location : "India"
  linkedin : "kartikeychauhan"
  github   : "kartikey-chauhan"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/kartikey-chauhan"

plugins:
  - jekyll-feed
  - jekyll-include-cache


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
